### ISSUE TITLE
SignalR Chat Test????

### ISSUE THREAD

**Issue by Da-Geek** [devedse/DeveLanCacheUI_Frontend#14]
Why does the LancacheUI Frontend have "SignalR" integrated?

What value does the "SignalR Chat Test" give a LancacheUI "that lets you see what's happening inside your LanCache application"?

is there an option to disable it/turn it off/remove it ?

**Comment by devedse** [comment]
SignalR is the framework used to automatically update the frontend when the backend changes. The SignalR chat is just a demo that I started with. I should remove it.

**Comment by devedse** [comment]
Ok I removed it in the latest version :)
